FROM mcr.microsoft.com/playwright:v1.52.0-jammy

WORKDIR /app

RUN apt-get update && apt-get install -y \
    g++ \
    make \
    cmake \
    unzip \
    libcurl4-openssl-dev \
    autoconf \
    libtool \
    ca-certificates \
    curl \
    gnupg \
    wget \
    && rm -rf /var/lib/apt/lists/*

# --- Install Google Chrome Stable ---
RUN install -m 0755 -d /etc/apt/keyrings && \
curl -fsSL https://dl.google.com/linux/linux_signing_key.pub \
    | gpg --dearmor -o /etc/apt/keyrings/google-linux-signing-key.gpg && \
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-linux-signing-key.gpg] http://dl.google.com/linux/chrome/deb/ stable main" \
    > /etc/apt/sources.list.d/google-chrome.list && \
apt-get update && apt-get install -y google-chrome-stable && \
rm -rf /var/lib/apt/lists/*

ENV NPM_CONFIG_CACHE=/tmp/.npm
ENV PLAYWRIGHT_BROWSERS_PATH=0

RUN npm install aws-lambda-ric -g

ENV IS_DOCKER=true

COPY *.json ./
COPY *.ts ./
COPY db/*.ts ./db/
COPY gmail/*.ts ./gmail/
COPY gmail/*.json ./gmail/
COPY model/*.ts ./model/
COPY websocket/*.ts ./websocket/

RUN npm ci
RUN npm run build

RUN npx playwright install --with-deps
#RUN npx playwright install chromium

RUN cp *.json dist/

ENTRYPOINT ["/bin/npx", "aws-lambda-ric"]
CMD ["dist/main_coupang.handler"]

